name: clay_containers
description: Easily create custom neumorphic container widgets for your own unique design.
version: 0.1.1
homepage: https://michaelcharl.es

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: